### ISSUE TITLE
tap action possible?

### ISSUE THREAD

**Issue by Protoncek** [stefmde/HomeAssistantSimpleDateTimeClockCard#2]
Hello!
I just discovered your card, congrats, great work, i was just looking for a clock with smaller seconds. 
I have two questions, though: 
- is it possible to have a "tap_action" on this card? I would use it for toggle my bedroom lights;
- i managed to change font color and card background with card mod. Is is possible to change seconds font separately?

Thanks!

**Comment by stefmde** [comment]
Hi!
- I don't know how to implement something like that. And if so I think it must be universal to use it for multiple things devices/links and so on.
- The time has no class or id to identify exactly for overrides of styles. You can dim it so it's lighter

**Comment by Protoncek** [comment]
Ok, thanks. I figured out color change, that was my main thing. If tap is not an option i can live with that…
Thanks for explanation!
